export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'

export const UPDATE_TABLE = 'UPDATE_TABLE'
export const UPDATE_VIEW = 'UPDATE_VIEW'
